package game.model.weather;

public enum TileAppearance {
    GRASS_NORMAL_1, GRASS_NORMAL_2, GRASS_NORMAL_3,
    GRASS_WET_1, GRASS_WET_2,
    GRASS_DRY_1, GRASS_DRY_2, GRASS_DRY_3,

    SOIL_TOP_LEFT, SOIL_TOP_LEFT_WET_1, SOIL_TOP_LEFT_WET_2,
    SOIL_TOP_RIGHT, SOIL_TOP_RIGHT_WET_1, SOIL_TOP_RIGHT_WET_2,
    SOIL_BOT_LEFT, SOIL_BOT_LEFT_WET_1, SOIL_BOT_LEFT_WET_2,
    SOIL_BOT_RIGHT, SOIL_BOT_RIGHT_WET_1, SOIL_BOT_RIGHT_WET_2,
    SOIL_TOP, SOIL_TOP_WET_1, SOIL_TOP_WET_2,
    SOIL_BOT, SOIL_BOT_WET_1, SOIL_BOT_WET_2,
    SOIL_LEFT, SOIL_LEFT_WET_1, SOIL_LEFT_WET_2,
    SOIL_RIGHT, SOIL_RIGHT_WET_1, SOIL_RIGHT_WET_2,
    SOIL_CENTER, SOIL_CENTER_WET_1, SOIL_CENTER_WET_2,

    SOIL_HEAT_TOP_LEFT, SOIL_HEAT_TOP_LEFT_WET_1, SOIL_HEAT_TOP_LEFT_WET_2,
    SOIL_HEAT_TOP_RIGHT, SOIL_HEAT_TOP_RIGHT_WET_1, SOIL_HEAT_TOP_RIGHT_WET_2,
    SOIL_HEAT_BOT_LEFT, SOIL_HEAT_BOT_LEFT_WET_1, SOIL_HEAT_BOT_LEFT_WET_2,
    SOIL_HEAT_BOT_RIGHT, SOIL_HEAT_BOT_RIGHT_WET_1, SOIL_HEAT_BOT_RIGHT_WET_2,
    SOIL_HEAT_TOP, SOIL_HEAT_TOP_WET_1, SOIL_HEAT_TOP_WET_2,
    SOIL_HEAT_BOT, SOIL_HEAT_BOT_WET_1, SOIL_HEAT_BOT_WET_2,
    SOIL_HEAT_LEFT, SOIL_HEAT_LEFT_WET_1, SOIL_HEAT_LEFT_WET_2,
    SOIL_HEAT_RIGHT, SOIL_HEAT_RIGHT_WET_1, SOIL_HEAT_RIGHT_WET_2,
    SOIL_HEAT_CENTER, SOIL_HEAT_CENTER_WET_1, SOIL_HEAT_CENTER_WET_2
}
